### PR TITLE
Fix #252 processed cube

### LINKED ISSUE #252: Missing columns for `be_alientaxa_cube_processed.parquet`
Given [this script](https://github.com/inbo/aspbo/blob/uat/src/cube_preprocessing.Rmd#L161), the file `be_alientaxa_cube_processed.parquet` on the bucket should contain extra columns `isFlanders,isWallonia,isBrussels,gemeente,provincie,gewest`.
However when I load the data, I don't get these (anymore):

```
> library(alienSpecies)
> tmpData <- loadTabularData(type = "occurrence")
occurrence data: 38940 observaties dateren van voor 1950 en zijn dus uitgesloten
> colnames(tmpData)
[1] "year"           "cell_code1"     "taxonKey"       "n"             
[5] "scientificName" "classKey"       "cell_code10"   
```

The file seems to be changed early september:

```
> tmpTable <- aws.s3::get_bucket_df(
      bucket = config::get("bucket", file = system.file("config.yml", package = "alienSpecies")))
> tmpTable[grep("cube", tmpTable$Key), ]
                                  Key             LastModified
7               be_alientaxa_cube.csv 2023-10-11T19:49:50.000Z
8   be_alientaxa_cube_processed.RData 2024-07-19T08:58:44.000Z
9 be_alientaxa_cube_processed.parquet 2024-09-03T08:29:44.000Z
```

@soriadelva Can we try to run the script again to see whether it still applies for the latest scripts/data?

Note: The file `be_alientaxa_cube_processed.RData` does contain all the extra columns. So the script might have been run on an old version of the R package `alienSpecies`?

```
> readS3(file = "be_alientaxa_cube_processed.RData")
> colnames(rawData)
 [1] "year"           "cell_code1"     "taxonKey"       "n"             
 [5] "isFlanders"     "isWallonia"     "isBrussels"     "gemeente"      
 [9] "provincie"      "gewest"         "scientificName" "classKey"      
[13] "cell_code10"   
```

### PR DESCRIPTION
**Pull request by mvarewyck**
null

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
If I'm correct this action should place the files with the correct columns on the bucket [cube preprocessing](https://github.com/inbo/aspbo/actions/workflows/cube_preprocessing.yaml) and running this action: https://github.com/inbo/aspbo/actions/workflows/upload_files_processing.yaml afterwards should not overwrite it. 

@mvarewyck can you confirm ? 

meanwhile this action should upload the translation files for testing the translations: [upload_files_direct](https://github.com/inbo/aspbo/actions/workflows/upload_files_direct.yaml)

**Comment by mvarewyck** [comment]
> If I'm correct this action should place the files with the correct columns on the bucket [cube preprocessing](https://github.com/inbo/aspbo/actions/workflows/cube_preprocessing.yaml) and running this action: https://github.com/inbo/aspbo/actions/workflows/upload_files_processing.yaml afterwards should not overwrite it.
> 
> @mvarewyck can you confirm ?

Yes, the 2nd action should no longer overwrite it, because I removed the "cube creation step" from it.

**Comment by SanderDevisscher** [comment]
🤞

**Comment by SanderDevisscher** [comment]
[upload_files_processing](https://github.com/inbo/aspbo/actions/workflows/upload_files_processing.yaml)

**Comment by SanderDevisscher** [comment]
ran the action on the wrong branch [cube preprocessing](https://github.com/inbo/aspbo/actions/workflows/cube_preprocessing.yaml)

**Comment by SanderDevisscher** [comment]
[upload_files_processing](https://github.com/inbo/aspbo/actions/workflows/upload_files_processing.yaml)

**Comment by mvarewyck** [comment]
@SanderDevisscher Processed cube has expected format now.

**Review by SanderDevisscher — APPROVED** [review]

**Pull request merged**
