### PR TITLE
expand download to include belgium

### LINKED ISSUE #187: gbif data download should be expanded to include the whole of Belgium
https://github.com/inbo/aspbo/blob/31a11d94ea29f03d5fc45665b9a0b632ce5a6f1f/src/Vespa%20velutina%20management/get_data_from_gbif.Rmd#L46

- [ ] expand download 
- [ ] rerun [vespa action](https://github.com/inbo/aspbo/actions/workflows/get_vespa_velutina_management.yaml)

### LINKED ISSUE #204: Fix translations that cause the get vespa velutina management data flow to fail
These occur in the points.geojeson file in the level3Name column. 

- Brussel / Bruxelles
- Elsene / Ixelles

### PR DESCRIPTION
**Pull request by SanderDevisscher**
fixes #187

may be merged if run ([get_vespa_velutina_management](https://github.com/inbo/aspbo/actions/workflows/get_vespa_velutina_management.yaml)) succeeds

### CODE REVIEW

**Review by soriadelva — CHANGES_REQUESTED** [review]
I get an error message when running the script for lines 40-43 (create the polygon). `Error in FUN(X[[i]], ...) : !anyNA(x) is not TRUE.` This may be linked to the warning in the lines above: 
`coord_matrix <- matrix(as.numeric(unlist(strsplit(coord_pairs, " "))), ncol = 2, byrow = TRUE)
Warning messages:
1: In matrix(as.numeric(unlist(strsplit(coord_pairs, " "))), ncol = 2,  :
  NAs introduced by coercion`

**Comment by SanderDevisscher** [comment]
The Same error kills the workflow

**Review by soriadelva — DISMISSED** [review]
The whole download works well but I do get an error during the plotting part with leaflet:
`Error in polygonData.default(data) : 
  Don't know how to get path data from object of class character`

I guess this part could be erased? although it is a nice check to see that the belgian outline is correct.

**Comment by SanderDevisscher** [comment]
> The whole download works well but I do get an error during the plotting part with leaflet: `Error in polygonData.default(data) : Don't know how to get path data from object of class character`
> 
> I guess this part could be erased? although it is a nice check to see that the belgian outline is correct.

This part is for testing only, the chunk is also in `eval = FALSE`  & should be run on 
```
bel <- st_read("./data/output/UAT_processing/grid/gewestbel.shp") %>% 
  st_simplify(dTolerance = 10) %>% 
  st_make_valid() %>% 
  st_union() %>% 
  st_as_sf() %>% 
  st_simplify(dTolerance = 1500) %>%
  st_cast(to = "POLYGON")
```
so dropping 
```
st_as_sfc() %>% 
  st_as_text() 
```

modify/delete still ?

**Comment by soriadelva** [comment]
> > The whole download works well but I do get an error during the plotting part with leaflet: `Error in polygonData.default(data) : Don't know how to get path data from object of class character`
> > I guess this part could be erased? although it is a nice check to see that the belgian outline is correct.
> 
> This part is for testing only, the chunk is also in `eval = FALSE` & should be run on
> 
> ```
> bel <- st_read("./data/output/UAT_processing/grid/gewestbel.shp") %>% 
>   st_simplify(dTolerance = 10) %>% 
>   st_make_valid() %>% 
>   st_union() %>% 
>   st_as_sf() %>% 
>   st_simplify(dTolerance = 1500) %>%
>   st_cast(to = "POLYGON")
> ```
> 
> so dropping
> 
> ```
> st_as_sfc() %>% 
>   st_as_text() 
> ```
> 
> modify/delete still ?

Hmm, I think I would still modify, by adding the object that can be used for testing to the code chunk (maybe renaming it slighthly to bel_test and then call on that in leaflet)? So the code can be used as is for testing when needed.

**Comment by SanderDevisscher** [comment]
> > > The whole download works well but I do get an error during the plotting part with leaflet: `Error in polygonData.default(data) : Don't know how to get path data from object of class character`
> > > I guess this part could be erased? although it is a nice check to see that the belgian outline is correct.
> > 
> > 
> > This part is for testing only, the chunk is also in `eval = FALSE` & should be run on
> > ```
> > bel <- st_read("./data/output/UAT_processing/grid/gewestbel.shp") %>% 
> >   st_simplify(dTolerance = 10) %>% 
> >   st_make_valid() %>% 
> >   st_union() %>% 
> >   st_as_sf() %>% 
> >   st_simplify(dTolerance = 1500) %>%
> >   st_cast(to = "POLYGON")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so dropping
> > ```
> > st_as_sfc() %>% 
> >   st_as_text() 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > modify/delete still ?
> 
> Hmm, I think I would still modify, by adding the object that can be used for testing to the code chunk (maybe renaming it slighthly to bel_test and then call on that in leaflet)? So the code can be used as is for testing when needed.

I'll add this textually.

**Comment by SanderDevisscher** [comment]
#204 should be fixed as well. New run has been triggered https://github.com/inbo/aspbo/actions/runs/9795013414

**Review by soriadelva — APPROVED** [review]

**Pull request merged**
